. ../common.env

for i in $DB_INSTANCE_LIST
do
u="${i}DU"

cat <<EOF
CREATE ROLE "$u" WITH LOGIN INHERIT PASSWORD '$PG_DB_USER_PASSWORD';
EOF

psql <<EOF
CREATE ROLE "$u" WITH LOGIN INHERIT PASSWORD '$PG_DB_USER_PASSWORD';
EOF

done
